### ISSUE TITLE
Make this a general script to be used by any other project.

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix-beta-version#2]
Looked into doing something similar for [Focus](https://github.com/mozilla-mobile/focus-android/) that needs to verify the beta versions similarly to know when to uplift strings ([PR adding the workflow for syncing strings](https://github.com/mozilla-mobile/focus-android/pull/7124)) but it seems like we can adapt this project to use `GITHUB_REPOSITORY` instead of 

https://github.com/mozilla-mobile/fenix-beta-version/blob/0bab3e17e9047f00a5f1e00a880be76045fa70b8/src/fenix-beta-version.py#L61-L69

to avoid having to duplicate this for every other Mozilla project that needs this functionality.

**Comment by escapewindow** [comment]
Sure, we can make this generic.
At that point the repo name will be a misnomer, but that's probably ok. We are planning on moving off of the github actions at some point.
